/** Machine-readable description of the Notion graph. No personal plan content. */
export const LEARNING_MODEL = {
  summary:
    "The app answers what to learn next and how it moves the career forward. Career Goal is the destination. Learning Plan is the parent. Learning Agenda, Learning Tasks, and Learning Milestones each relate to Learning Plan. There is one Learning Tasks database, and its Learning Item property is a relation. When is the scheduled start. Duration (min) is the length. Career Progress moves Beginner → Working → Applied → Expert. Applied means the skill was used in real work.",
  hierarchy: ["Career Goal", "Learning Plan", "Agenda", "Tasks", "Milestones", "Evidence", "Career Progress"],
  careerProgress: ["Beginner", "Working", "Applied", "Expert"],
  parent: {
    database: "Learning Plan",
    role: "One course, event, book, or other learning item.",
  },
  agenda: {
    database: "Learning Agenda",
    relation: "Learning Item",
    fields: {
      Name: "Session title",
      Start: "When it starts",
      End: "When it ends",
      "Agenda Type": "Session, Workshop, Networking, Travel, Meal, Reflection, or Work buffer",
      Plan: "Intention: Attend Live, Watch Recording, Alternative, Optional, or Skip",
      Attendance: "Outcome: Planned, Attended, Watched, Missed, or Cancelled. Set this after the session.",
      Priority: "Must, High, Medium, or Optional",
      Track: "Subject tags",
      Venue: "Where it happens",
      Speaker: "Who leads it",
      Link: "Session or recording URL",
      Notes: "Preparation notes",
      Takeaways: "What was learned",
      "Follow-up": "What to do next",
    },
  },
  milestones: {
    database: "Learning Milestones",
    relation: "Learning Items",
    fields: {
      Milestone: "What you are trying to achieve",
      Status: "Not Started, In Progress, Achieved, or At Risk",
      Target: "The date it should be reached",
      Capability: "The career capability it belongs to",
      "Progress %": "How far the milestone itself has moved",
      "Success Criteria": "What done means",
      Evidence: "Proof the milestone was reached",
      "Learning Items": "Relation to the Learning Plan rows that contribute",
    },
  },
  tasks: {
    database: "Learning Tasks",
    relation: "Learning Item",
    fields: {
      Name: "Task title",
      Status: "To Do, In Progress, Done, or Skipped. Set Done or Skipped when it is finished.",
      "Task Type": "Logistics types such as Booking or Preparation, or execution types Learn, Practice, Build, Review, and Apply. Use the options on this database.",
      Priority: "Must, Core, High, Medium, or Optional",
      Due: "Date it should be finished",
      When: "Scheduled start. Use this for the day plan. Due stays the finish date.",
      "Duration (min)": "How long the task should take",
      Link: "Related URL",
      Notes: "Extra detail",
    },
  },
  api: {
    item: "GET /api/items/{id} includes agenda and tasks for that parent",
    monitor: "GET /api/monitor lists open sessions and open tasks",
    updateAgenda: "PATCH /api/agenda/{id} with attendance, plan, notes, takeaways, or followUp",
    updateTask: "PATCH /api/tasks/{id} with status, notes, or due",
    createTask: "POST /api/tasks with name and optional due, learningItemId, priority, taskType, notes",
    captureNote: "POST /api/notes with target item or task, id, label, and text",
    shape: "GET /api/model",
    career: "GET /career is the path, skills gap, and evidence",
    week: "GET /week is the weekly plan",
  },
} as const;
